//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public int id { get; set; }
        public string Name { get; set; }
        public decimal SalePrice { get; set; }
        public decimal UniPrice { get; set; }
        public int Quantity { get; set; }
        public decimal Profit { get; set; }
    }
}
